# Generated by Django 4.2 on 2024-08-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_contactus_status_alter_service_status_and_more'),
        ('blog', '0002_remove_blogdetail_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='blog')),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('image_publisher', models.ImageField(default='default.jpg', upload_to='blog')),
                ('category', models.ManyToManyField(to='blog.category')),
                ('comments', models.ManyToManyField(to='blog.comment')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.team')),
            ],
        ),
    ]
