# Generated by Django 4.2 on 2024-08-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
    ]
