# Generated by Django 4.2 on 2024-08-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Twitter',
            new_name='twitter',
        ),
    ]
