# Generated by Django 4.2 on 2024-08-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_rename_twitter_team_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='linkdin',
            new_name='linkedin',
        ),
    ]
