# Generated by Django 4.2 on 2024-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_rename_linkdin_team_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
