# Generated by Django 4.2 on 2024-08-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_contactus_status_alter_service_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='Skill',
            field=models.ManyToManyField(to='root.skill'),
        ),
    ]
